version: '3'

services:

  db:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'light174'
    volumes:
      - ./db_django:/var/lib/mysql
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  
  web:
    build: ./popit_api
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./popit_api:/web_django
    ports:
      - '8000:8000'
    depends_on:
      - db
