# Generated by Django 3.2.5 on 2021-07-10 12:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Toy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('image', models.FileField(blank=True, upload_to='', verbose_name='Изображение')),
                ('coins_by_click', models.FloatField(verbose_name='Монет/клик')),
                ('pop_count', models.IntegerField(verbose_name='Количество пупырок')),
                ('flipings_before_ad', models.IntegerField(verbose_name='Количество переворачиваний до рекламы')),
            ],
            options={
                'verbose_name': 'Игрушка',
                'verbose_name_plural': 'Игрушки',
            },
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.FilePathField(blank=True, verbose_name='Изображение')),
                ('coins_by_sec', models.FloatField(verbose_name='Монет/сек')),
            ],
            options={
                'verbose_name': 'Улучшение',
                'verbose_name_plural': 'Улучшения',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vk_id', models.CharField(db_index=True, max_length=12, verbose_name='VK ID')),
                ('full_name', models.CharField(max_length=128, verbose_name='Полное имя')),
                ('date_of_birth', models.DateField(default=datetime.date(1900, 1, 1), verbose_name='Дата рождения')),
                ('coins_available', models.FloatField(default=0, verbose_name='Монеты')),
                ('score', models.FloatField(default=0, verbose_name='Счёт')),
                ('coins_by_sec', models.FloatField(default=0.001, verbose_name='Монет/сек')),
                ('coins_by_click', models.FloatField(default=0.001, verbose_name='Монет/клик')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('last_date', models.DateTimeField(auto_now=True, verbose_name='Дата последней активности')),
                ('buyed_updates', models.JSONField(default=list, verbose_name='Купленные улучшения')),
                ('buyed_toys', models.JSONField(default=list, verbose_name='Купленные игрушки')),
                ('active_toy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_v1.toy')),
                ('friends', models.ManyToManyField(blank=True, to='api_v1.User')),
                ('refer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referals', to='api_v1.user')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
