# Generated by Django 3.2.5 on 2021-07-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friend', to='api_v1.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='vk_id',
            field=models.IntegerField(db_index=True, primary_key=True, serialize=False, verbose_name='VK ID'),
        ),
    ]
