# Generated by Django 3.2.5 on 2021-07-08 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='active_toy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='api_v1.toy', verbose_name='Текущая игрушка'),
        ),
        migrations.AlterField(
            model_name='user',
            name='buyed_toys',
            field=models.JSONField(blank=True, verbose_name='Купленные игрушки'),
        ),
        migrations.AlterField(
            model_name='user',
            name='buyed_updates',
            field=models.JSONField(blank=True, verbose_name='Купленные улучшения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='coins_available',
            field=models.FloatField(default=0, verbose_name='Монеты'),
        ),
        migrations.AlterField(
            model_name='user',
            name='coins_by_click',
            field=models.FloatField(default=0.001, verbose_name='Монет/клик'),
        ),
        migrations.AlterField(
            model_name='user',
            name='coins_by_sec',
            field=models.FloatField(default=0.001, verbose_name='Монет/сек'),
        ),
        migrations.AlterField(
            model_name='user',
            name='score',
            field=models.FloatField(default=0, verbose_name='Счёт'),
        ),
    ]
