# Generated by Django 3.2.5 on 2021-07-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0003_auto_20210710_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='toy',
            name='base_price',
            field=models.FloatField(default=0, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='update',
            name='base_price',
            field=models.FloatField(default=0, verbose_name='Цена'),
        ),
    ]
