# Generated by Django 3.2.5 on 2021-07-10 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0004_auto_20210710_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='loged',
            field=models.BooleanField(default=False, verbose_name='Залогинен'),
        ),
    ]
