# Generated by Django 3.2.5 on 2021-07-08 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0004_alter_user_active_toy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='buyed_toys',
            field=models.JSONField(default='{}', verbose_name='Купленные игрушки'),
        ),
        migrations.AlterField(
            model_name='user',
            name='buyed_updates',
            field=models.JSONField(default='{}', verbose_name='Купленные улучшения'),
        ),
    ]
