# Generated by Django 3.2.5 on 2021-07-11 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0005_user_loged'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='loged',
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('vk_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v1.user')),
            ],
        ),
    ]
