# Generated by Django 3.2.5 on 2021-07-11 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0006_auto_20210711_0819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='date_created',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='vk_id',
            new_name='user',
        ),
    ]
