# Generated by Django 3.2.5 on 2021-07-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0007_auto_20210711_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='user',
        ),
        migrations.AddField(
            model_name='session',
            name='vk_id',
            field=models.IntegerField(db_index=True, default=0, verbose_name='VK ID'),
        ),
    ]
