# Generated by Django 3.2.5 on 2021-07-11 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0008_auto_20210711_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='id',
        ),
        migrations.AlterField(
            model_name='session',
            name='vk_id',
            field=models.IntegerField(db_index=True, primary_key=True, serialize=False, verbose_name='VK ID'),
        ),
    ]
