# Generated by Django 3.2.5 on 2021-07-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0009_auto_20210711_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='toy',
            name='referals_need',
            field=models.IntegerField(default=0, verbose_name='Необходимо рефералов'),
        ),
    ]
